import type { Metadata } from "next";

import "./globals.css";
import SessionProvider from "../providers/SessionProvider";
import Navbar from "@/components/Navbar";
import { jost } from "@/components/font";
import CartProvider from "@/providers/CartProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <CartProvider>
          <body
            className={`${jost.className} antialiased max-w-7xl mx-auto bg-white`}
          >
            <Navbar />
            <main className="mt-16">{children}</main>
          </body>
        </CartProvider>
      </SessionProvider>
    </html>
  );
}
