import type { Metadata } from "next";

import "./globals.css";

import Navbar from "@/components/Navbar";
import { jost, lexendDeca, oswald } from "@/components/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.className} antialiased max-w-7xl mx-auto`}>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
